Feature
anx333y/fifth-esoft-DZ-react pull request #1
Opened 2024-05-27 16:38 UTC by anx333y

Вот описание

2024-06-01 16:26 UTC, anx333y commented
добавил новое в эту ветку, не знаю отобразится ли это в пулл реквесте

2024-06-08 19:24 UTC, Unaccommodating requested changes
Молодец! Работу принял

2024-06-08 19:24 UTC, Unaccommodating commented on src/api/filmData.js
> +		...filmData,
```
     ...filmData,
    "name": filmData.name || filmData.alternativeName || "Безымянный",
    "type": filmData.type ? switchTypes(filmData.type) : "Что-то неизведанное...",
    "year": filmData.year || '',
```

и т.д.

2024-06-08 19:24 UTC, Unaccommodating commented on src/components/buisness/Film/Film.jsx
> +		console.log(film)
console.log

2024-06-08 19:24 UTC, Unaccommodating commented on src/components/buisness/Film/Film.jsx
> +			const posterUrl = film.poster
`const posterUrl = film.poster ? film.poster.previewUrl || film.poster.url : null;
`

2024-06-08 19:24 UTC, Unaccommodating commented on src/components/buisness/Film/Film.jsx
> +	useEffect(() => {
почему бы не объединить в один хук?

2024-06-08 19:24 UTC, Unaccommodating commented on src/components/buisness/FilmCard/FilmCard.jsx
> +		const posterUrl = props.poster
ну ты понял

2024-06-08 19:24 UTC, Unaccommodating commented on src/components/buisness/Search/SearchSelect.jsx
> +	useEffect(() => {
```
useEffect(() => {
  if (Array.isArray(thisParams) && thisParams.length) {
    if (selectChecked.length === 0) {
      setSelectCheked(
        thisParams.map(param =>
          nameFor === 'types' ? switchTypes(param) : param
        )
      );
    }
  } else if (selectChecked.length !== 0) {
    setSelectCheked([]);
  }
}, [thisParams]);

```

2024-06-08 19:24 UTC, Unaccommodating commented on src/components/buisness/Search/SearchSelect.jsx
> +	useEffect(() => {
некоторые проверки ненужные

2024-06-08 19:24 UTC, Unaccommodating commented on src/components/buisness/SimilarFilmList/SimilarFilmList.css
> +/* .film-card{
зачем это?

2024-08-04 20:48 UTC, merged